services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DISABLE_AUTH=false
      - PROXY_DOMAIN=dev.fsdh-dhsf.science.cloud-nuage.canada.ca
      - SUDO_PASSWORD=password
      - PWA_APPNAME=Code Server
      - CERTFILE=
      - KEYFILE=
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:code-server-python3
      - INSTALL_PACKAGES=iputils-ping|dnsutils|tcptraceroute
    volumes:
      - ${WEBAPP_STORAGE_HOME}/config:/config
      - ${WEBAPP_STORAGE_HOME}/projects:/projects
    ports:
      - "3838:8443"
    restart: unless-stopped
